### ISSUE TITLE
Breakseq, HYDRA and cnmops errors from Docker

### ISSUE THREAD

**Issue by arumds** [TheJacksonLaboratory/SVE#40]
Hi all,

I tried using the SVE docker version  on non-human genomes and  3 SV methods breakseq, hydra and cnmops failed with the below error messages. Could anyone hint to fix these:

```
**Breakseq**

$ singularity_wrapper exec /Tools/sve.sif /tools/SVE/bin/sve call -r ROSY.fa -g others /sv-callers-testing/H027.bam -a breakseq-o /sv-callers-testing/ -t 20

call error: INFO 2021-05-21 10:49:35,211 /tools/SVE/src/breakseq2/scripts/run_breakseq2.py Command-line: /tools/SVE/src/breakseq2/scripts/run_breakseq2.py --bwa /tools/SVE/src/bwa/bwa --samtools /tools/SVE/src/samtools/samtools --reference ROSY.fa --work S35/ --min_span 2 --window 500 --min_overlap 2 --junction_length 1000 —bams H027.bam --nthreads 20
ERROR 2021-05-21 10:49:35,341 breakseq2_workflow   Atleast one of the breakpoint FASTA or GFF must be specified

**Cnmops**
$ singularity_wrapper exec /Tools/sve.sif /tools/SVE/bin/sve call -r ROSY.fa -g others /sv-callers-testing/H027.bam -a cnmops-o /sv-callers-testing/ -t 20

Error in if (WL >= sl[i]) {: missing value where TRUE/FALSE needed

-------------------------------error----------------------------
Error in cat(list(...), file, sep, fill, labels, append) : 
  argument 1 (type 'list') cannot be handled by 'cat'
Execution halted

message: 
code: 1
output:

**HYDRA:**

$ singularity_wrapper exec /Tools/sve.sif /tools/SVE/bin/sve call -r ROSY.fa -g others /sv-callers-testing/H027.bam -a hydra -o /sv-callers-testing/ -t 20

making the hydra configuration
/usr/local/bin/python /tools/SVE/src/hydra/scripts/make_hydra_config.py -i /S17/bam.stub -s 100000 -n 1$
extracting discordants for sample0
/usr/local/bin/python /tools/SVE/src/hydra/scripts/extract_discordants.py -c /S17/bam.stub.config -d sa$
call error: Traceback (most recent call last):
  File "/tools/SVE/src/hydra/scripts/extract_discordants.py", line 212, in <module>
    main()
  File "/tools/SVE/src/hydra/scripts/extract_discordants.py", line 204, in main
    discordant_bam_query_sort = query_sort_discordant(discordant_bam, opts.mem)
  File "/tools/SVE/src/hydra/scripts/extract_discordants.py", line 128, in query_sort_discordant
    subprocess.call(shlex.split(sortCmd))
  File "/usr/local/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

Apart from Hydra and cnmops, Breakseq error seems to be requring some input file. How could it be generated?

**Comment by ccastane9** [comment]
I receive the same issues with all 3 of these.

**Comment by arumds** [comment]
I am still eagerly waiting to hear from the developers.
