### ISSUE TITLE
Error with sve call

### ISSUE THREAD

**Issue by hd4git** [TheJacksonLaboratory/SVE#8]
Hi,

I installed SVE using docker, but I get this error while calling variants:

`loaded param_map from: cnvnator.json
Traceback (most recent call last):
  File "/media/NVMe1.2/Tools/SVE/SVE/scripts/sve.py", line 105, in <module>
    st = stage.Stage(paras['algorithm'],dbc)

  File "/media/NVMe1.2/Tools/SVE/SVE/scripts/../stage.py", line 17, in __init__
    self.__link__ = c(wrapper,dbc,retrieve,upload,params)

  File "/media/NVMe1.2/Tools/SVE/SVE/scripts/../stages/cnvnator.py", line 16, in __init__
    stage_wrapper.Stage_Wrapper.__init__(self,wrapper,dbc,retrieve,upload,params)

  File "/media/NVMe1.2/Tools/SVE/SVE/scripts/../stages/stage_wrapper.py", line 42, in __init__
    self.tools = tools.TOOLS

AttributeError: 'module' object has no attribute 'TOOLS' `

Command used is:
`python /media/NVMe1.2/Tools/SVE/SVE/scripts/sve.py call -r $ref -o variants/sv/ -t 10 -a cnvnator -g others $sample\.bam`

Is it some installation problem? Can you please suggest what needs to be done.

Thanks!!

**Comment by lslochov** [comment]
Hi there, I've noticed that you're using "-g others" in your command line. The "-g" option is expecting a specific reference genome, like hg19 or hg38. The use of the word "others" in the readme was meant to indicate that there are other possible reference genomes one can use here; "others" is not an actual name for a reference genome. Please try using an actual reference genome and see if that helps.

**Comment by jingydz** [comment]
Hi, I have the same error with you.@hd4git Do you find the reasons?
`$ python ../scripts/sve.py align -r hg38.fa A2413_L2L4_324324.R1.fastq.gz A2413_L2L4_324324.R2.fastq.gz
loaded param_map from: bwa_index.json
Traceback (most recent call last):
  File "../scripts/sve.py", line 43, in <module>
    st = stage.Stage('bwa_index',dbc)
  File "/home/zhangjj/software/SVE/SVE/scripts/../stage.py", line 17, in __init__
    self.__link__ = c(wrapper,dbc,retrieve,upload,params)
  File "/home/zhangjj/software/SVE/SVE/scripts/../stages/bwa_index.py", line 14, in __init__
    stage_wrapper.Stage_Wrapper.__init__(self,wrapper,dbc,retrieve,upload,params)
  File "/home/zhangjj/software/SVE/SVE/scripts/../stages/stage_wrapper.py", line 42, in __init__
    self.tools = tools.TOOLS
AttributeError: 'module' object has no attribute 'TOOLS'
`
